import { PageHeader } from "@/components/UI";
export default function Guide() {
  return (
    <article className="guide-article">
      <PageHeader title="Usage guide" />
      <section><h2 className="text-xl font-bold">Opening</h2>
        <p>Run locally with <code>npm install</code>, <code>npm run ingest</code>, <code>npm run dev</code>, then open http://localhost:3000. Jurors need no paid subscription or personal Claude/OpenAI account. Hosted AI access is provided by the deployment/team&apos;s server configuration and supplied demo code. For local AI features, configure <code>ANTHROPIC_API_KEY</code> (or <code>OPENAI_API_KEY</code> + <code>LLM_MODEL</code>) in <code>.env.local</code>.</p>
        <p>Without a configured AI provider, browsing, evidence and search still work. Chat, building the knowledge base, automatic impact analysis, answer recomputation and AI-assisted update interpretation require a configured provider.</p></section>
      <section><h2 className="text-xl font-bold">Navigation</h2>
        <p>The sidebar follows the project: overview, one-page brief, questions, timeline, decisions, contradictions, actions, sources, team, adding new information, and this guide. Ask from the header or the Questions page to add a sourced answer underneath the existing questions. The header shows which version you are looking at.</p></section>
      <section><h2 className="text-xl font-bold">Finding evidence</h2>
        <p>Every statement carries an evidence chip such as <strong>M04 · L23</strong>. Clicking it opens the file at that exact line, page, cell or screenshot row, highlighted. Locators: <code>L23</code> line, <code>¶3</code> email paragraph, <code>p.1</code> PDF page, <code>F7</code> spreadsheet cell, <code>row 4</code> screenshot row. The Sources page searches every line of every file, accents optional.</p></section>
      <section><h2 className="text-xl font-bold">Asking questions</h2>
        <p>Use the question bar (English or French). Answers come only from the NOVA files; each citation is checked against the source text and removed if it cannot be found.</p></section>
      <section><h2 className="text-xl font-bold">Adding new information</h2>
        <p>With a configured AI provider, open &quot;Add new information&quot;, drop the file, review the three columns (problem status, prior decision still in force, new proposal), the affected items, the actions and the guardrails, then publish. Each publication is a new version (U001, U002…); the baseline stays untouched.</p>
        <p>Without a provider, source files can still be uploaded, supported text extracted and reviewed, and published as a new version. The manual fallback edits only problem status, prior decisions and proposal text. It has no controls for citations, proposer/authority metadata, formal new decisions, affected questions/conditions/actions, condition status changes, new actions, or revised answers/brief. Empty impact fields mean analysis was not performed, not that no items are affected. Publishing runs code guardrails; it does not complete impact analysis or recompute answers. A configured demo code is still required for upload and publication.</p>
        <p>New images need a vision-capable provider for transcription. Scanned PDFs without a text layer and unreadable formats are retained for manual review, not automatically read. Existing baseline screenshot transcriptions remain available.</p></section>
      <section><h2 className="text-xl font-bold">Tools and manual steps</h2>
        <p>Next.js, TypeScript, Tailwind, mailparser, unpdf, SheetJS, mammoth, and an LLM (Anthropic or any OpenAI-compatible model) for chat, screenshot reading and update analysis. The ten answers, timeline, decisions, contradictions, actions and brief were curated by the team and every quote is machine-verified against the corpus (<code>npm run ingest</code>). The eight baseline screenshots were transcribed and checked by a human. Every update is reviewed by a person before publishing.</p></section>
      <section className="guide-limits"><h2 className="text-xl font-bold">Limits and uncertain information</h2>
        <ul className="list-disc pl-5">
          <li>Model answers can still misinterpret; citations are checked, interpretation is not.</li>
          <li>Screenshots show past states; ticket status prevails.</li>
          <li>Each answer lists what the files do not document; the system says so instead of guessing.</li>
          <li>The knowledge base is generated by AI from the raw files and scored against a hand-curated answer key; the score is shown on the Questions page.</li>
        </ul></section>
    </article>
  );
}
